[A] latattemptelision() could use more love

MorphPossibilityObject.getlatinbaseform() needs work per-misceo
MorphPossibilityObject.getlatinbaseform() needs work permixtā, per-misceo
MorphPossibilityObject.getlatinbaseform() needs work praevortēmur, prae-verto
MorphPossibilityObject.getlatinbaseform() needs work dissīderent, dis-sido

[B] similarly
MorphPossibilityObject.getbaseform() is confused ἐνέρριπτεν, ἐν, ἐν-ῥίπτω ['ἐνέρριπτεν', 'ἐν', 'ἐν-ῥίπτω']
MorphPossibilityObject.getbaseform() is confused ἐνέρριψεν, ἐν, ἐν-ῥίπτω ['ἐνέρριψεν', 'ἐν', 'ἐν-ῥίπτω']
MorphPossibilityObject.getbaseform() is confused ἐνέρριψαν, ἐν, ἐν-ῥίπτω ['ἐνέρριψαν', 'ἐν', 'ἐν-ῥίπτω']
MorphPossibilityObject.getbaseform() is confused ἐνέρριψε, ἐν, ἐν-ῥίπτω ['ἐνέρριψε', 'ἐν', 'ἐν-ῥίπτω']

[C] resetsession

resetsession will reload '/' without clearing date range from html (but the range has been reset)
a second click will clear the display
js async timing issue, it seems
irritating to avoid "return redirect(url_for('frontpage'))" which is so simple and easy to call

[D] platform specific bug? Ryzen vs FreeBSD vs threads

[resolved? enabled virtualization in the BIOS when playing with bhyve and the problem went away]

workonsimplesearch() (and probably its kin)

a very odd bug in here on a Ryzen 1600x running FreeBSD 11.1: you can search for "mentior" 10x and
somewhere in those trials the search will fail: one of the threads will get stuck in this function
this cannot be reproduced on macOS 10.13.2 with identical versions of python and postgres installed...
this bug is not in Hipparchia? presumably it also does not affect just this function

you will not trigger the bug with the following number of workers set in config.py
    1
    2
    3
    4
at 5 and 6 you get fails: often right away
but then you can do more searches that will work for a while
then you will fail
then you can do more searches on top of this
this will leave you with two zombie threads and two eternally updating polls

PooledCoonections can give some insight into the failure:

success: lots of connections return
    connection returned to pool: cdxuheaxllwh
    connection returned to pool: lntxrxfazsae
    connection returned to pool: ycxhhbbfddjb
    connection returned to pool: plzhaoxekeif
    connection returned to pool: fqdeflurdxda
    connection returned to pool: pouehdobwalh
    connection returned to pool: qtuwhufcywwq
    connection returned to pool: zhqqklbrpcly
    connection returned to pool: ngtlbdtntppq
    connection returned to pool: gtilspjppzdt
    connection returned to pool: mkmentgxkmqc
    connection returned to pool: nnijmjgqylgs
    connection returned to pool: minqxopiocju
    connection returned to pool: sphojeucdudr
    connection returned to pool: eisdjqpreipq
    connection returned to pool: hhjryxvpohsi
    [22/Mar/2018 08:28:05] "GET /executesearch/1521721684476?skg=%CE%A8%CE%B7%CF%86%CE%B9%CF%B2%CE%B1%CE%BC%CE%AD%CE%BD%CE%B7%CF%B2%20%CE%B4%E1%BD%B2%20%CF%84%E1%BF%86%CF%B2%20%CE%B2%CE%BF%CF%85%CE%BB%E1%BF%86%CF%B2 HTTP/1.1" 200 -

freeze: 8 connections return; there are 10 workers...
    connection returned to pool: bomicybcsucs
    connection returned to pool: oonokovlecod
    connection returned to pool: jzeoyhukohml
    connection returned to pool: mlngnennlyif
    connection returned to pool: zkwxcabpeucx
    connection returned to pool: urcwtmarsxns
    connection returned to pool: ufowvlsfrcer
    connection returned to pool: qlscphoqoqpc

the choke seems more likely when you get many results really fast: some sort of problem with the lock on the managed list?


[Ε] DeprecationWarning

this is emerging from one of the installed packages?

/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py:191: DeprecationWarning: bad escape \s
  return _compile(pattern, flags).sub(repl, string, count)
/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py:191: DeprecationWarning: bad escape \s
  return _compile(pattern, flags).sub(repl, string, count)
/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py:191: DeprecationWarning: bad escape \s
  return _compile(pattern, flags).sub(repl, string, count)
/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py:191: DeprecationWarning: bad escape \s
  return _compile(pattern, flags).sub(repl, string, count)
/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py:191: DeprecationWarning: bad escape \s
  return _compile(pattern, flags).sub(repl, string, count)

